/**
 * URL shortener API
 * URL shortener
 *
 * OpenAPI spec version: 1.0.1-oas3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface  ShortResponse {
  sequence: string;
  shortedUrl: string;
  qrReferenceUrl: string;

  infoUrlRequestChannel: string;
  infoUrlListenChannel: string;
  infoUrlErrorChannel: string;

  dailyStatsOperatingSystemUrl: string;
  dailyStatsBrowserUrl: string;

  globalStatsRequestOperatingSystemChannel: string;
  globalStatsRequestBrowserChannel: string;
  globalStatsListenChannel: string;
  globalStatsErrorChannel: string;

  globalStatsOperatingSystemChangesListenChannel: string;
  globalStatsBrowserChangesListenChannel: string;

  adsUrl: string;
}
